export const projects = [
    {
        id: 1,
        name: 'Dumbways - Dummy 1',
        startDate: '2023-01-01',
        endDate: '2023-02-01',
        summary: 'Dummy App is the first project in my journey at Dumbways.id to become a Fullstack Developer.',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, esse asperiores veritatis sequi animi aspernatur quis veniam facilis corporis maxime. Ipsam, voluptatum recusandae magni assumenda labore dolores ex error enim minus veritatis, fuga eum facilis dicta ea pariatur non commodi! Temporibus recusandae quos tempore mollitia id sit, nihil repellat error dolor reprehenderit ea adipisci quaerat dolorum libero neque corporis ratione. Eaque, velit ullam hic vel, soluta temporibus corrupti deserunt sapiente praesentium repudiandae enim similique sint, voluptas cum! Deserunt nesciunt natus soluta officia minima explicabo veniam vero delectus nemo, nostrum dolorem molestiae nisi velit eius, ipsa sequi ex fugiat maxime amet? Veritatis corrupti unde sapiente earum, ex laboriosam officiis deleniti, voluptatibus, ratione quasi eveniet excepturi magnam. Quo cumque aliquid aperiam nihil. Temporibus magnam repellat ducimus fuga, et amet odit laboriosam dolorem vel, fugiat, molestiae sint cumque ipsam nostrum unde. Perferendis beatae soluta expedita? Deserunt placeat possimus recusandae tempora! Nisi libero placeat sit voluptate perspiciatis ipsam corporis sunt, laborum vitae! Suscipit, ipsam velit. Magni, exercitationem saepe, odio quae dolorum, eos nulla officiis quibusdam tenetur quaerat nesciunt architecto commodi earum recusandae. Ad in voluptatibus quaerat assumenda facere consectetur odit, aliquam excepturi eaque iure vel eligendi nemo modi quasi odio. Tempore quis sed natus, ea ab excepturi rerum molestiae voluptatum aliquam quam. Dignissimos, vel molestiae facilis repellat illo nisi consectetur. Aspernatur adipisci consequatur, iusto placeat reiciendis esse voluptates molestiae numquam quo odio quis quod commodi consequuntur corrupti ea debitis earum ab dolor. Corrupti, culpa aliquam nisi eius ratione quia tempore neque molestias quod voluptatibus?',
        technologies: ['node-js', 'react', 'js'],
        image: './assets/img/laptop-1.jpeg'
    },
    {
        id: 2,
        name: 'Dumbways - Dummy 2',
        startDate: '2023-02-01',
        endDate: '2023-04-01',
        summary: 'Dummy App is the second project in my journey at Dumbways.id to become a Fullstack Developer.',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, esse asperiores veritatis sequi animi aspernatur quis veniam facilis corporis maxime. Ipsam, voluptatum recusandae magni assumenda labore dolores ex error enim minus veritatis, fuga eum facilis dicta ea pariatur non commodi! Temporibus recusandae quos tempore mollitia id sit, nihil repellat error dolor reprehenderit ea adipisci quaerat dolorum libero neque corporis ratione. Eaque, velit ullam hic vel, soluta temporibus corrupti deserunt sapiente praesentium repudiandae enim similique sint, voluptas cum! Deserunt nesciunt natus soluta officia minima explicabo veniam vero delectus nemo, nostrum dolorem molestiae nisi velit eius, ipsa sequi ex fugiat maxime amet? Veritatis corrupti unde sapiente earum, ex laboriosam officiis deleniti, voluptatibus, ratione quasi eveniet excepturi magnam. Quo cumque aliquid aperiam nihil. Temporibus magnam repellat ducimus fuga, et amet odit laboriosam dolorem vel, fugiat, molestiae sint cumque ipsam nostrum unde. Perferendis beatae soluta expedita? Deserunt placeat possimus recusandae tempora! Nisi libero placeat sit voluptate perspiciatis ipsam corporis sunt, laborum vitae! Suscipit, ipsam velit. Magni, exercitationem saepe, odio quae dolorum, eos nulla officiis quibusdam tenetur quaerat nesciunt architecto commodi earum recusandae. Ad in voluptatibus quaerat assumenda facere consectetur odit, aliquam excepturi eaque iure vel eligendi nemo modi quasi odio. Tempore quis sed natus, ea ab excepturi rerum molestiae voluptatum aliquam quam. Dignissimos, vel molestiae facilis repellat illo nisi consectetur. Aspernatur adipisci consequatur, iusto placeat reiciendis esse voluptates molestiae numquam quo odio quis quod commodi consequuntur corrupti ea debitis earum ab dolor. Corrupti, culpa aliquam nisi eius ratione quia tempore neque molestias quod voluptatibus?',
        technologies: ['node-js', 'vuejs', 'js'],
        image: './assets/img/laptop-2.jpeg'
    },
    {
        id: 3,
        name: 'Dumbways - Dummy 3',
        startDate: '2023-04-01',
        endDate: '2023-05-01',
        summary: 'Dummy App is the third project in my journey at Dumbways.id to become a Fullstack Developer.',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, esse asperiores veritatis sequi animi aspernatur quis veniam facilis corporis maxime. Ipsam, voluptatum recusandae magni assumenda labore dolores ex error enim minus veritatis, fuga eum facilis dicta ea pariatur non commodi! Temporibus recusandae quos tempore mollitia id sit, nihil repellat error dolor reprehenderit ea adipisci quaerat dolorum libero neque corporis ratione. Eaque, velit ullam hic vel, soluta temporibus corrupti deserunt sapiente praesentium repudiandae enim similique sint, voluptas cum! Deserunt nesciunt natus soluta officia minima explicabo veniam vero delectus nemo, nostrum dolorem molestiae nisi velit eius, ipsa sequi ex fugiat maxime amet? Veritatis corrupti unde sapiente earum, ex laboriosam officiis deleniti, voluptatibus, ratione quasi eveniet excepturi magnam. Quo cumque aliquid aperiam nihil. Temporibus magnam repellat ducimus fuga, et amet odit laboriosam dolorem vel, fugiat, molestiae sint cumque ipsam nostrum unde. Perferendis beatae soluta expedita? Deserunt placeat possimus recusandae tempora! Nisi libero placeat sit voluptate perspiciatis ipsam corporis sunt, laborum vitae! Suscipit, ipsam velit. Magni, exercitationem saepe, odio quae dolorum, eos nulla officiis quibusdam tenetur quaerat nesciunt architecto commodi earum recusandae. Ad in voluptatibus quaerat assumenda facere consectetur odit, aliquam excepturi eaque iure vel eligendi nemo modi quasi odio. Tempore quis sed natus, ea ab excepturi rerum molestiae voluptatum aliquam quam. Dignissimos, vel molestiae facilis repellat illo nisi consectetur. Aspernatur adipisci consequatur, iusto placeat reiciendis esse voluptates molestiae numquam quo odio quis quod commodi consequuntur corrupti ea debitis earum ab dolor. Corrupti, culpa aliquam nisi eius ratione quia tempore neque molestias quod voluptatibus?',
        technologies: ['node-js', 'react', 'js'],
        image: './assets/img/laptop-3.jpeg'
    },
    {
        id: 4,
        name: 'Dumbways - Dummy 4',
        startDate: '2023-05-01',
        endDate: '2023-07-01',
        summary: 'Dummy App is the fourth project in my journey at Dumbways.id to become a Fullstack Developer.',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, esse asperiores veritatis sequi animi aspernatur quis veniam facilis corporis maxime. Ipsam, voluptatum recusandae magni assumenda labore dolores ex error enim minus veritatis, fuga eum facilis dicta ea pariatur non commodi! Temporibus recusandae quos tempore mollitia id sit, nihil repellat error dolor reprehenderit ea adipisci quaerat dolorum libero neque corporis ratione. Eaque, velit ullam hic vel, soluta temporibus corrupti deserunt sapiente praesentium repudiandae enim similique sint, voluptas cum! Deserunt nesciunt natus soluta officia minima explicabo veniam vero delectus nemo, nostrum dolorem molestiae nisi velit eius, ipsa sequi ex fugiat maxime amet? Veritatis corrupti unde sapiente earum, ex laboriosam officiis deleniti, voluptatibus, ratione quasi eveniet excepturi magnam. Quo cumque aliquid aperiam nihil. Temporibus magnam repellat ducimus fuga, et amet odit laboriosam dolorem vel, fugiat, molestiae sint cumque ipsam nostrum unde. Perferendis beatae soluta expedita? Deserunt placeat possimus recusandae tempora! Nisi libero placeat sit voluptate perspiciatis ipsam corporis sunt, laborum vitae! Suscipit, ipsam velit. Magni, exercitationem saepe, odio quae dolorum, eos nulla officiis quibusdam tenetur quaerat nesciunt architecto commodi earum recusandae. Ad in voluptatibus quaerat assumenda facere consectetur odit, aliquam excepturi eaque iure vel eligendi nemo modi quasi odio. Tempore quis sed natus, ea ab excepturi rerum molestiae voluptatum aliquam quam. Dignissimos, vel molestiae facilis repellat illo nisi consectetur. Aspernatur adipisci consequatur, iusto placeat reiciendis esse voluptates molestiae numquam quo odio quis quod commodi consequuntur corrupti ea debitis earum ab dolor. Corrupti, culpa aliquam nisi eius ratione quia tempore neque molestias quod voluptatibus?',
        technologies: ['node-js', 'react', 'js'],
        image: './assets/img/laptop-4.jpg'
    },
    {
        id: 5,
        name: 'Dumbways - Dummy 5',
        startDate: '2023-07-01',
        endDate: '2024-01-01',
        summary: 'Dummy App is the fifth project in my journey at Dumbways.id to become a Fullstack Developer.',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus, esse asperiores veritatis sequi animi aspernatur quis veniam facilis corporis maxime. Ipsam, voluptatum recusandae magni assumenda labore dolores ex error enim minus veritatis, fuga eum facilis dicta ea pariatur non commodi! Temporibus recusandae quos tempore mollitia id sit, nihil repellat error dolor reprehenderit ea adipisci quaerat dolorum libero neque corporis ratione. Eaque, velit ullam hic vel, soluta temporibus corrupti deserunt sapiente praesentium repudiandae enim similique sint, voluptas cum! Deserunt nesciunt natus soluta officia minima explicabo veniam vero delectus nemo, nostrum dolorem molestiae nisi velit eius, ipsa sequi ex fugiat maxime amet? Veritatis corrupti unde sapiente earum, ex laboriosam officiis deleniti, voluptatibus, ratione quasi eveniet excepturi magnam. Quo cumque aliquid aperiam nihil. Temporibus magnam repellat ducimus fuga, et amet odit laboriosam dolorem vel, fugiat, molestiae sint cumque ipsam nostrum unde. Perferendis beatae soluta expedita? Deserunt placeat possimus recusandae tempora! Nisi libero placeat sit voluptate perspiciatis ipsam corporis sunt, laborum vitae! Suscipit, ipsam velit. Magni, exercitationem saepe, odio quae dolorum, eos nulla officiis quibusdam tenetur quaerat nesciunt architecto commodi earum recusandae. Ad in voluptatibus quaerat assumenda facere consectetur odit, aliquam excepturi eaque iure vel eligendi nemo modi quasi odio. Tempore quis sed natus, ea ab excepturi rerum molestiae voluptatum aliquam quam. Dignissimos, vel molestiae facilis repellat illo nisi consectetur. Aspernatur adipisci consequatur, iusto placeat reiciendis esse voluptates molestiae numquam quo odio quis quod commodi consequuntur corrupti ea debitis earum ab dolor. Corrupti, culpa aliquam nisi eius ratione quia tempore neque molestias quod voluptatibus?',
        technologies: ['node-js', 'vuejs', 'js'],
        image: './assets/img/laptop-5.jpg'
    },
]